type Permission = "crm:read" | "email:draft";
type RiskState = "Aligned" | "Overextended" | "Blocked";

interface UserContext {
  id: string;
  email: string;
  permissions: Permission[];
}

interface WorkflowConfig {
  id: string;
  intent: string;
  requiredPermissions: Permission[];
  autonomyLevel: number;
  tools: string[];
  writeAccess: boolean;
  requiresApproval: boolean;
  inputs: {
    region: string;
    period: string;
  };
}

interface RunReport {
  runId: string;
  user: UserContext;
  workflow: WorkflowConfig;
  permissionPassed: boolean;
  missingPermissions: Permission[];
  riskState: RiskState;
  validationPassed: boolean;
  estimatedCostUsd: number;
  finalOutput?: {
    summary: string;
    emailDraft: string;
  };
  auditTrail: string[];
}

function createRunId(): string {
  return `run_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
}

function createUserContext(): UserContext {
  return {
    id: "user_osa_local",
    email: "osa@example.local",
    permissions: ["crm:read", "email:draft"]
  };
}

function createWorkflow(): WorkflowConfig {
  return {
    id: "mock-crm-summary",
    intent: "Create a sales summary from mock CRM data and prepare an email draft.",
    requiredPermissions: ["crm:read", "email:draft"],
    autonomyLevel: 2,
    tools: ["mock.crm.salesSummary"],
    writeAccess: false,
    requiresApproval: false,
    inputs: {
      region: "EU",
      period: "2026-Q2"
    }
  };
}

function checkPermissions(user: UserContext, workflow: WorkflowConfig) {
  const missing = workflow.requiredPermissions.filter(
    (permission) => !user.permissions.includes(permission)
  );

  return {
    passed: missing.length === 0,
    missing
  };
}

function scoreRisk(workflow: WorkflowConfig): RiskState {
  const riskScore = workflow.autonomyLevel * 10 + workflow.tools.length * 8 + (workflow.writeAccess ? 30 : 0);
  const coverageScore = 20 + 20 + 15 + (workflow.requiresApproval ? 30 : 0);

  if (workflow.writeAccess && !workflow.requiresApproval) return "Blocked";
  if (riskScore >= 70 && coverageScore < 70) return "Overextended";
  return "Aligned";
}

function mockCrmSalesSummary(input: WorkflowConfig["inputs"]) {
  return {
    region: input.region,
    period: input.period,
    totalRevenue: 128500,
    dealsClosed: 17,
    topAccount: "Northstar Manufacturing"
  };
}

function validateFinalOutput(summary: string, emailDraft: string): boolean {
  return summary.length > 20 && emailDraft.includes("Subject:");
}

async function runReliabilityKernel(): Promise<RunReport> {
  const auditTrail: string[] = [];
  const runId = createRunId();
  const user = createUserContext();
  const workflow = createWorkflow();

  auditTrail.push("Run created.");
  auditTrail.push(`Identity context attached: ${user.email}.`);
  auditTrail.push(`Workflow loaded: ${workflow.id}.`);

  const permission = checkPermissions(user, workflow);
  auditTrail.push(`Permission check: ${permission.passed ? "passed" : "blocked"}.`);

  const riskState = scoreRisk(workflow);
  auditTrail.push(`Risk state: ${riskState}.`);

  if (!permission.passed || riskState === "Blocked") {
    return {
      runId,
      user,
      workflow,
      permissionPassed: permission.passed,
      missingPermissions: permission.missing,
      riskState,
      validationPassed: false,
      estimatedCostUsd: 0,
      auditTrail
    };
  }

  const crm = mockCrmSalesSummary(workflow.inputs);
  auditTrail.push("Governed tool executed: mock.crm.salesSummary.");

  const summary = `Sales summary for ${crm.region} / ${crm.period}: ${crm.dealsClosed} deals closed, estimated revenue $${crm.totalRevenue}. Top account: ${crm.topAccount}.`;

  const emailDraft = [
    "Subject: Sales Summary Update",
    "",
    "Hi team,",
    "",
    summary,
    "",
    "This is a mock draft generated by AI OS Reliability Kernel v0.1.",
    "",
    "Regards,",
    "AI OS"
  ].join("\n");

  const validationPassed = validateFinalOutput(summary, emailDraft);
  auditTrail.push(`Validation: ${validationPassed ? "passed" : "failed"}.`);

  const estimatedCostUsd = 0.0031;
  auditTrail.push(`Cost estimated: ${estimatedCostUsd} USD.`);

  return {
    runId,
    user,
    workflow,
    permissionPassed: permission.passed,
    missingPermissions: permission.missing,
    riskState,
    validationPassed,
    estimatedCostUsd,
    finalOutput: {
      summary,
      emailDraft
    },
    auditTrail
  };
}

const report = await runReliabilityKernel();

console.log("\nAI OS Reliability Kernel v0.1\n");
console.log(`Run ID: ${report.runId}`);
console.log(`User: ${report.user.email}`);
console.log(`Workflow: ${report.workflow.id}`);
console.log(`Risk State: ${report.riskState}`);
console.log(`Permission Check: ${report.permissionPassed ? "Passed" : "Blocked"}`);
console.log(`Validation: ${report.validationPassed ? "Passed" : "Failed"}`);
console.log(`Estimated Cost: ${report.estimatedCostUsd.toFixed(4)} USD`);

if (report.finalOutput) {
  console.log("\nFinal Output:");
  console.log(report.finalOutput.summary);
}

console.log("\nAudit Trail:");
for (const event of report.auditTrail) {
  console.log(`- ${event}`);
}
console.log("");
